### ISSUE TITLE
RedirectHandler and caching redirects

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-design#1]
https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/RedirectHandler.md#performance-considerations

I don't think we should be caching requests. From my recollection and subsequent search of the Graph docs, I'm not finding any r[edirects other than 302s](https://github.com/microsoftgraph/microsoft-graph-docs/search?p=1&q=302&type=&utf8=%E2%9C%93). I'm fairly confident that we do encounter 304s from time to time. I do not think Graph responds with 301 and 308. I don't think there are any permanent redirects. 

@vikyding

**Comment by darrelmiller** [comment]
@MIchaelMainer As we discussed, caching permanent redirects is not an essential feature.  Based on my brief analysis there are services doing them, but it would be good to understand what specific endpoints they are for and why they are used.  Curiously 304 is not actually a redirect but a response to a conditional request. We will be able to consider providing support for 304s when/if we introduce a private caching layer into the middleware pipeline.
