### ISSUE TITLE
msgraph.go

### ISSUE THREAD

**Issue by yaegashi** [microsoftgraph/msgraph-sdk-design#28]
Here's yet another effort to implement golang client library much like #7.

https://github.com/yaegashi/msgraph.go

Any comments and suggestions on code generation strategy and library specific features are welcome.  And it would be great if it could serve in some way for adding golang support to [the official code generator](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator).

**Comment by MIchaelMainer** [comment]
@yaegashi I'm sorry that we have followed up with you. First off, thank you for sharing your effort and leadership in creating a Go library for Microsoft Graph. Go is on our roadmap, we just haven't funded it yet. 

A primary goal for the Microsoft Graph client libraries is to try to balance having shared architectural design while maintain true to the expected developer experience for a platform/language. Using the [SDK Architecture](https://github.com/microsoftgraph/msgraph-sdk-design#microsoft-graph-sdks---requirements-and-design) diagram is a good start. I imagine you already looked at that. 

My opinions are marked with <MO>, as there is some disagreement on these points.

Ideally we'd have a core library that can be a stand alone client for Microsoft Graph. It wraps the native HTTP APIs, provides a pre-configured client via a factory, a middleware pipeline, an auth provider interface, response handler, etc. <MO> I prefer the model we have for the [JavaScript client library](https://github.com/microsoftgraph/msgraph-sdk-javascript) where the core library has request builders for OData constructs, and the developer is responsible for building the URI. Our generated request builders are a super leaky abstraction that requires the developer to go learn what each dot-segment means, which should lead them to the docs, which will then lead them to the URL form. At that point, they can copy and paste the URL into their code. Plus, it makes for a much cleaner object model, and we will have better quality code snippets in the documentation.</MO>. 

I'd highly suggest that generated model libraries be separated from the generated request builders if we were to generate the request builders (<MO>which, I hope we don't</MO>). This way, for the set of customers who don't want to use the request builders, they can use the generated models with the core library, or with their own client. It would be straightforward to support the Go models in the generator. 

You should also consider all of the extensibility points (we haven't explicitly defined those, we really should). Bundling workflow into tasks (perhaps a workflow engine and template), model extensions, request builder extension, middleware, custom handlers, custom serialization, etc.

In the world of client libraries, there are those that never use them and code to the service API, some that will use part of the client libraries, and others who want to use all of it. Ultimately, client libraries should reduce impedance to fulfilling a solution. People will use the best available to them according to their preference. 

I have a lot more to add, but I have to get to work. Again, thank you for your effort.

**Comment by MIchaelMainer** [comment]
@funkeyfreak

**Comment by MIchaelMainer** [comment]
Go msgraph libraries: https://github.com/search?l=Go&q=msgraph&type=Repositories
