### ISSUE TITLE
Can I use that SDK with the old azure graph (graph.windows.net) ? 

### ISSUE THREAD

**Issue by irinatarn** [microsoftgraph/msgraph-sdk-design#33]
Can I use that SDK with the old azure graph (graph.windows.net) ?

**Comment by MIchaelMainer** [comment]
Hello @irinatarn 
The graph.windows.net endpoint has been deprecated. No one should use it at this point. The Microsoft Graph SDKs are only intended to be used with the graph.microsoft.com endpoint.
