### ISSUE TITLE
Getting exception on page iterator usage.

### ISSUE THREAD

**Issue by dondeetan** [microsoftgraph/msgraph-sdk-design#41]
When using the pageiterator class, I get the following exception: 

Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: Request_UnsupportedQuery
Message: Unable to execute query; invalid page token specified.
Inner error:
	AdditionalData:
	date: 2021-02-05T17:24:36
	request-id: 8cff971b-8506-4c23-9cbc-51b52d1c758f
	client-request-id: 8cff971b-8506-4c23-9cbc-51b52d1c758f
ClientRequestId: 8cff971b-8506-4c23-9cbc-51b52d1c758f

Code is below: 

 serviceprincipals = (_ismocked) ? 
                await _graphserviceclient.ServicePrincipals.Request(requestOptions).Top(500).GetAsync() 
                : 
                await _graphserviceclient.ServicePrincipals.Request(requestOptions).Top(500).Header("ConsistencyLevel", "eventual").GetAsync();
                

                var pageIterator = PageIterator<ServicePrincipal>
                    .CreatePageIterator(_graphserviceclient, serviceprincipals, (sp) => {                            
                            var someobject = new SomeObject { 
                                id = Guid.NewGuid().ToString(),
                                spnid = sp.Id,
                                spnappid = sp.AppId,
                                name = sp.DisplayName,
                                status = RequestStatus.Active.ToString(),
                                description = sp.Description
                            };
                            serviceprincipals.Add(someobject);
                            return true;
                    });

                await pageIterator.IterateAsync();

When I get the initial collection for the service principals, I'm getting the results however using the pageiterator throws the above exception.

**Comment by pschaeflein** [comment]
Take a look at https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/884

**Comment by dondeetan** [comment]
I'll refactor the code to make sure of NextPageRequest call and pass headers. Will get back. Thank you!

**Comment by dondeetan** [comment]
Got this working: 

 do
                    {
                        if (serviceprincipals.Count != 0)
                        {                            
                            //Cast to custom type
                            var currentrange = serviceprincipals.Select(someobject=> new SomeObject{ 
                                id = Guid.NewGuid().ToString(),
                                spnid = someobject.Id,
                                spnappid = someobject.AppId,
                                name = someobject.DisplayName,
                                status = someobject.Active.ToString(),
                                description = someobject.Description
                            });
                            //Add All Fetched VWAC Service Principals
                            customobjects.AddRange(currentrange);
                        }
                        
                        //Loop through the graph service principal results and get next result sets
                        if (serviceprincipals.NextPageRequest != null)                
                            serviceprincipals = await serviceprincipals.NextPageRequest.Header("ConsistencyLevel", "eventual").GetAsync();
                        else 
                            serviceprincipals = null;
                    } 
                while (serviceprincipals != null);

**Comment by dondeetan** [comment]
This works now....

```
                bool requestConfiguratorInvoked = false;
                Func<IBaseRequest, IBaseRequest> requestConfigurator = (request) =>
                {
                    requestConfiguratorInvoked = true;
                    request.Header("ConsistencyLevel", "eventual");
                    return request;
                };


                var pageIterator = PageIterator<ServicePrincipal>
                    .CreatePageIterator(_graphserviceclient, serviceprincipals, (sp) => {              
                          var someobject = new SomeObject { 
                            id = Guid.NewGuid().ToString(),
                            spnid = sp.Id,
                            spnappid = sp.AppId,
                            name = sp.DisplayName,
                            status = RequestStatus.Active.ToString(),
                            description = sp.Description
                        };
                        serviceprincipals.Add(someobject);
                        return true;
                    },requestConfigurator);
                    
                await pageIterator.IterateAsync();
```

Thank you!

**Comment by dondeetan** [comment]
Issue is closed with the above resolution
