### ISSUE TITLE
outlook email graph api Encrypted ?

### ISSUE THREAD

**Issue by abhishekujjain** [microsoftgraph/msgraph-sdk-design#51]
I am looking at documentation for the service is this outlook email graph API and could not find if the email service is encrypted or not?

We want to send sensitive information via email wanted to get clarity on that.

**Comment by baywet** [comment]
@abhishekujjain Sorry for the late response. We're not tracking customer questions here, this repo is only internal design guidelines for the SDKs.
The best thing to do for those sorts of question is to ask them [in dedicated the Q&A forum](https://learn.microsoft.com/en-us/answers/tags/283/microsoft-graph-mail-api/) which gets attention from the service team.
Closing.
