### ISSUE TITLE
Golang client library

### ISSUE THREAD

**Issue by j0hnsmith** [microsoftgraph/msgraph-sdk-design#7]
I started writing a go client library, generating the code based on the [xml api description](https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/v1.0_metadata.xml). I got quite far

* all the api types/enums with fields annotated (~265)
* client with authorization
* service for each entity set
* get & list calls for all types
* related calls eg user.ownedDevices

 ...to the point where I was ready to start testing the requests/responses however I don't have an account, even if I signed up my account would be empty. 

 Is there any way I can get a test/dev account that's populated with some data so I can continue?

**Comment by darrelmiller** [comment]
Hey @j0hnsmith this sounds great.  You can sign up for a developer Office 365 account here https://developer.microsoft.com/en-us/office/dev-program

**Comment by j0hnsmith** [comment]
Thanks @darrelmiller, I've signed up, I see there's a one year trial account but I'm guessing that will be empty, do you have any dev tools/scripts to populate accounts with data? I also saw the 30 days of msgraph blog posts which looks like it has some useful background info.

**Comment by MIchaelMainer** [comment]
@funkeyfreak because he'll appreciate this since he started with https://github.com/funkeyfreak/msgraph-sdk-go.

@j0hnsmith We don't have any scripts for populating the demo tenants. I recently had a conversation with a team that is looking to fix this.

**Comment by jpleau** [comment]
@j0hnsmith 

Hi. Is your go code available publicly by any chance?

**Comment by j0hnsmith** [comment]
@jpleau it's not, it's in a WIP state too so messy, not sure anyone else would understand it.

**Comment by jpleau** [comment]
Fair enough, thanks

**Comment by j0hnsmith** [comment]
I had come back to this recently, used the sample data packs to create users etc etc. @yaegashi beat me to it :), had a quick read of the msgraph.go code, lots of it is very similar to mine, great work 👍
