### ISSUE TITLE
Retry-after is not exposed header so cannot be used because of CORS

### ISSUE THREAD

**Issue by montella1507** [microsoftgraph/msgraph-sdk-design#76]
Regarding the documentation, you should use Retry-after header, when you got status 429. 

However, Retry-after header is not listed under "Access-Control-Expose-Headers" header so it CANNOT BE USED in SPA  application because of CORS policy. 

**The documentation shall contain the information it is not usable in frontend applications at all - maybe it should contains the information that microsoft support employers are not helping, but forcing users to use GraphAPI SDK which doesn't help with that problem? Just to spare free time of both the microsoft support and graph api consumer?**

**Comment by baywet** [comment]
Hi @montella1507 sorry for the late response, we're not tracking customers questions in this repo which is dedicated to design guidelines for SDKs. The best things to do in those sorts of situations are either to open a support case or to [post in the dedicated Microsoft Q&A forum](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) to get attention from the service team.
Closing.
