### ISSUE TITLE
Microsoft booking - Getting/Editing staff members

### ISSUE THREAD

**Issue by Clapla** [microsoftgraph/msgraph-sdk-design#91]
Hello,

I am currently working on implementing Microsoft Booking functionality in our web app using the Microsoft.Graph sdk V.5.40 in C#. However, I’m facing an issue with retrieving data for booking staff members. When using the StaffMembersRequestBuilder of a BookingBusiness, I can only obtain a BookingStaffMemberBase object, which prevents me from accessing and editing all the information related to a booking staff member (such as Display Name, Email Address, etc.).

For example, in the following code snippet, I would expect to retrieve a BookingStaffMember object instead of a BookingStaffMemberBase:

BookingStaffMemberBase bookingStaffMemberBase = await graphClient.Solutions.BookingBusinesses[serviceRequest.BookingBusinessId]
           .StaffMembers[serviceRequest.StaffMemberId]
           .GetAsync();

My question is: How can we retrieve the complete data of a booking staff member once they have been added to the booking business, and how should we go about editing this information?

Thank you for your assistance.

**Comment by Yehiaelmatrwy2023** [comment]
Thankyou

**Comment by andrueastman** [comment]
Thanks for raising this @Clapla 

We'll close this for now as this is not the right place to raise this. 
However, please check out https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2354 for clarity on this. Or create an issue in the repo incase of any issues.
