### ISSUE TITLE
listitem: delta

### ISSUE THREAD

**Issue by RickL1234** [microsoftgraph/msgraph-sdk-design#93]
If this is not the correct place to ask this question, please let me know where to ask it that is more appropriate.

It appears that there was a listitem delta endpoint in the Beta version of the Microsoft Graph API.  However, it does not seem to exist in v1.0.  Was support for this functionality just dropped or is there another way to achieve the same or similar functionality?

Thanks,
Rick L.

**Comment by andrueastman** [comment]
Thanks for raising this @RickL1234 

Normally, new APIs will be onboarded on beta first and then later on be moved to the v1.0. With regards to the specific API, I would suggest asking the question at the link below to get feedback from the relevant API owners. 

https://learn.microsoft.com/en-us/answers/tags/161/ms-graph

Closing this for now as this isn't the right place for the issue/question.

**Comment by RickL1234** [comment]
Thanks!
